### ISSUE TITLE
req.flash() requires sessions 

### ISSUE THREAD

**Issue by DeepaliMahalde922** [airmiha/create-shopify-app#12]
Why I am getting this error. I have followed doc properly. Anyone can help?

![flash-error](https://user-images.githubusercontent.com/19953461/37552918-dfc7d02c-29e3-11e8-982d-733a1ea57817.png)

**Comment by protonhs** [comment]
hello!
Have you found a solution please? I'm getting the same error.

**Comment by DeepaliMahalde922** [comment]
Yeah! I've found it. This issue occurs due to improper configuration. Please try https://github.com/DeepaliMahalde922/createshopifyapp2

**Comment by airmiha** [comment]
Do you guys have Redis running in the background?

See this thread as an example of what can cause this error:

https://stackoverflow.com/questions/30563321/error-req-flash-requires-sessions/30563492
